Add 2nd pass testing and some cleanup in the GH actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,7 +7,7 @@ on:
   pull_request:
 
 jobs:
-  test:
+  fortify-tests:
     runs-on: ubuntu-latest
 
     steps:
@@ -23,9 +23,6 @@ jobs:
         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
         path: test
 
-    # - name: Install build dependencies
-    #   run: sudo apt-get update && sudo apt-get install -y python3-setuptools python3-dev
-
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
@@ -40,7 +37,7 @@ jobs:
     - name: Install dependencies
       run: pip install -r fortify/requirements.txt
 
-    - name: Run tests and compare results
+    - name: Run driver on tests once
       run: |
         mkdir -p reports
         for file in test/testfile_??.f*; do
@@ -67,8 +64,33 @@ jobs:
           fi
         done
 
-    - name: Show error log if differences found
-      run: cat reports/diff.log
+    - name: Run driver on tests twice
+      run: |
+        mkdir -p reports
+        for file in test/testfile_??.f*; do
+          base=$(basename "$file")
+          keyfile="test/keyfile_${base#testfile_}"
+          if [[ -f "$keyfile" ]]; then
+            echo "Running: python fortify/source/driver.py $file"
+            python3 fortify/source/driver.py "$file"
+            python3 fortify/source/driver.py "$file"
+            echo "Comparing $file with $keyfile"
+
+            # Use tee to capture and display diff output
+            diff "$file" "$keyfile" | tee reports/diff_${base#testfile_}.log
+            if [[ $? -ne 0 ]]; then
+              echo "Diff found for $file. See reports/diff_${base#testfile_}.log"
+              echo "Diff found for $file" >> reports/diff.log
+              exit 1
+            else
+              echo "No errors reported for $file"
+              echo "No errors reported for $file" >> reports/diff.log
+            fi
+          else
+            echo "Keyfile $keyfile not found for $file"
+            echo "Keyfile $keyfile not found for $file" >> reports/diff.log
+          fi
+        done
     
     - name: Upload reports as artifacts
       uses: actions/upload-artifact@v4
