comboyombo

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -112,6 +112,16 @@ jobs:
                   --comment_character "$comment_char" \
                   --continuation_character "$cont_char" \
                   --tab_length "$tab_len"
+                
+                # Use tee to capture and display diff output
+                diff "$file" "$keyfile" | tee reports/diff_${base#testfile_}.log
+                if [[ $? -ne 0 ]]; then
+                  echo "Diff found for $file. See reports/diff_${base#testfile_}.log"
+                  echo "Diff found for $file" >> reports/diff.log
+                  exit 1
+                else
+                  echo "No errors reported for $file" >> reports/diff.log
+                fi
 
                 # Increment the file number
                 num=$((num + 1))
